# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-12 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quanxian',
            options={'permissions': (('can_view', '查看'), ('can_add', '添加'), ('can_edit', '编辑'), ('can_delete', '删除'), ('can_super', '超级'))},
        ),
    ]
